services:
 # 開発用 Vite
  vite:
    image: node:20-alpine
    build:
      context: vite
    container_name: ORuCa_vite
    working_dir: /vite
    volumes:
      - ./vite:/vite:rw
      - vite_node_modules:/vite/node_modules
    ports:
      - "4000:4000"
    command: ["tail","-f","/dev/null"]
    networks:
      - backend
    profiles:
      - "dev"

  # 本番用 Nginx
  web:
    image: nginx:latest
    build: 
      context: web
    container_name: ORuCa_web
    ports:
      - "4040:80"
    volumes:
      - ./vite/dist:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - backend
    profiles:
      - "prod"

  mysql:
    build:
      context: mysql
      args:
        MYSQL_DATABASE : ${MYSQL_DATABASE}
        MYSQL_USER : ${MYSQL_USER}
        MYSQL_PASSWORD : ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
    container_name: ORuCa_mysql
    env_file:
      - .env
    volumes:
      - ./mysql/data/init.sql:/docker-entrypoint-initdb.d/init.sql  # SQLファイルをコンテナ内にマウント
      - mysql_data:/var/lib/mysql  # MySQLのデータを永続化
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - backend

  api:
    image: node:20-alpine
    build:
      context: api
    container_name: ORuCa_api
    working_dir: /api
    volumes:
      - ./api:/api:rw
      - api_node_modules:/api/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["tail","-f","/dev/null"]
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend

  nfc:
    image: python:3.13-alpine
    container_name: ORuCa_nfc
    build:
      context: nfc  # Dockerfileが存在するディレクトリ
    init: true # PID 1 問題を解決するらしい
    working_dir: /nfc
    volumes:
      - ./nfc:/nfc:rw
    ports:
      - "8000:8000"  # コンテナ内のポート8000をホストのポート8000にバインド
    environment:
      - TZ=Asia/Tokyo  # 必要に応じて環境変数の追加
    command: ["python","main.py"]
    depends_on:
      mysql:
        condition: service_healthy
    devices:
      - "/dev/bus/usb:/dev/bus/usb"  # USBデバイスをコンテナに渡す
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  vite_node_modules:
  api_node_modules:
  mysql_data:
