services:
 # 開発用 Vite
  vite:
    image: node:20
    container_name: ORuCa_vite
    working_dir: /app
    volumes:
      - ./vite:/app:rw
    ports:
      - "4000:4000"
    command: ["tail","-f","/dev/null"]
    networks:
      - backend
    profiles:
      - "dev"

  # 本番用 Nginx
  web:
    image: nginx:latest
    container_name: ORuCa_web
    ports:
      - "4000:80"
    volumes:
      - ./vite/dist:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - backend
    profiles:
      - "prod"


  mysql:
    build:
      context: mysql
      args:
        MYSQL_DATABASE : ${MYSQL_DATABASE}
        MYSQL_USER : ${MYSQL_USER}
        MYSQL_PASSWORD : ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
    container_name: ORuCa_mysql
    env_file:
      - .env
    volumes:
      - ./mysql/data/init.sql:/docker-entrypoint-initdb.d/init.sql  # SQLファイルをコンテナ内にマウント
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s
    networks:
      - backend

  api:
    image: node:20-alpine
    build:
      context: api
    container_name: ORuCa_api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend

  nfc:
    image: python:3.13-alpine
    container_name: ORuCa_nfc
    build:
      context: nfc  # Dockerfileが存在するディレクトリ
    working_dir: /app
    volumes:
      - ./nfc:/app:rw
    ports:
      - "8000:8000"  # コンテナ内のポート8000をホストのポート8000にバインド
    environment:
      - TZ=Asia/Tokyo  # 必要に応じて環境変数の追加
    command: ["python","main.py"]
    depends_on:
      mysql:
        condition: service_healthy
    devices:
      - "/dev/bus/usb:/dev/bus/usb"  # USBデバイスをコンテナに渡す
    networks:
      - backend


networks:
  backend:
    driver: bridge
